### ISSUE TITLE
Traefik is stopped even if no update is required

### ISSUE THREAD

**Issue by nfk** [bonddim/ansible-role-traefik#4]
An issue is spotted when I run the playbook without any changes or conf changes. In my case I use a stable version `v2.3.4` of traefik.
The role stop the service while no update is required, then it does not restart the service at the end.

```
TASK [bonddim.traefik : Get traefik version number] 
ok
TASK [bonddim.traefik : Stop service before update]
changed
TASK [bonddim.traefik : Download and extract archive]
ok
TASK [bonddim.traefik : Copy binary to install location]
ok
```

**Comment by bonddim** [comment]
@nfk , thank you for issue, and sorry for late response.
I have seen this problem once. And fixed it in [2.2.0](https://github.com/bonddim/ansible-role-traefik/releases/tag/2.2.0) release.
Reinstall role by running `ansible-galaxy install -f bonddim.traefik`
